apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing
  annotations:
    github.com/project-slug: jeffslofish/backstage-testing
spec:
  type: other
  lifecycle: unknown
  owner: test1
